### ISSUE TITLE
EnhancedArmaments-fabric-1.19.2  cant work

### ISSUE THREAD

**Issue by TAOYAOYAO1** [Nova-Committee/Enhanced-Armaments-Reload#11]
EnhancedArmaments-fabric-1.19.2-1.1.3.1 or EnhancedArmaments-fabric-1.19.2-1.1.3 ,it cant to work,我不知道你懂不懂中文，总的来说就是不能正常运行fabric版本的1.19.2，不管是不是最新版，无法正常启动，也没有报错信息

**Comment by TAOYAOYAO1** [comment]
我也在https://www.mcmod.cn/class/5938.html上面反应了，也有和我一样遭遇的人

**Comment by cnlimiter** [comment]
收到，正在修复

**Comment by cnlimiter** [comment]
已修复

**Comment by TAOYAOYAO1** [comment]
悲报，经过测试，剑和护甲没有问题，但是弓箭没有任何伤害，箭直接从怪物身上穿过去了，所以我删掉了mod之后，怪物又可以正常被弓箭攻击了，所以麻烦研究一下弓箭是什么情况

**Comment by TAOYAOYAO1** [comment]
> 已修复
悲报，经过测试，剑和护甲没有问题，但是弓箭没有任何伤害，箭直接从怪物身上穿过去了，所以我删掉了mod之后，怪物又可以正常被弓箭攻击了，所以麻烦研究一下弓箭是什么情况

**Comment by cnlimiter** [comment]
收到

**Comment by cnlimiter** [comment]
1.1.3.3版本已经修复

**Comment by TAOYAOYAO1** [comment]
1.1.3.3版本已经修复了弓箭的问题，但是同时又发现盔甲不会增加经验值了，请问该怎么办
