### ISSUE TITLE
[ fabric 1.19.2 ]can`t use command

### ISSUE THREAD

**Issue by AlenBeer** [Nova-Committee/Enhanced-Armaments-Reload#18]
/addlevel 
/changerarity 
When i use these  command,Prompt me:unknown or incomplete command,see below for error.
I don't know what the full command is.

**Comment by AlenBeer** [comment]
The mod version is fabric-1.19.2-1.1.3.3

**Comment by Gamemassa** [comment]
I'm getting this issue as well.

**Comment by Gamemassa** [comment]
@cnlimiter Could we get some clarification please?

**Comment by Gamemassa** [comment]
@MikhailTapio @cnlimiter Hello?
