### ISSUE TITLE
Request support of 1.20.1

### ISSUE THREAD

**Issue by IAALAI** [Nova-Committee/Enhanced-Armaments-Reload#26]
Request support of MC 1.20.1,forge 47

**Comment by IAALAI** [comment]
@cnlimiter 你好，仓库的管理员，我自己开发好了一个1.20.1的版本，我在我本地运行了，一切表现正常.代码在 https://github.com/IAALAI/Enhanced-Armaments-Reload  ，请求创建一个1.20版本的分支然后我PR过来

**Comment by cnlimiter** [comment]
> @cnlimiter 你好，仓库的管理员，我自己开发好了一个1.20.1的版本，我在我本地运行了，一切表现正常.代码在 https://github.com/IAALAI/Enhanced-Armaments-Reload ，请求创建一个1.20版本的分支然后我PR过来

已经开了分支
