### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by ghost** [Nova-Committee/Enhanced-Armaments-Reload#3]
版本：1165Forge
模组版本：EnhancedArmaments-forge-1.16.5-1.1.2
测试环境仅有增强装备重制版一个模组。
问题：
en_us下：
![image](https://user-images.githubusercontent.com/76616758/178134852-f51747dd-56f7-49eb-af3f-e839a02bbe38.png)
zh_cn下：
![image](https://user-images.githubusercontent.com/76616758/178134869-c02e2678-5667-407c-87b7-3e7b7d135381.png)
我的模组配置文件：https://pastebin.ubuntu.com/p/wp43zMybpS/

**Comment by cnlimiter** [comment]
没有复现出bug，可能是其他更改装备属性的模组冲突了吧

**Comment by VulpesStella** [comment]
如果高版本亦出现此问题，可尝试安装 [Attribute Tooltip Fix](https://www.mcmod.cn/class/7533.html)，如果可以解决，我们会考虑把它并入此模组。
