### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by ardissaps** [Nova-Committee/Enhanced-Armaments-Reload#5]
Scroll the log to very bottom :
https://paste.atlauncher.com/view/360609bc-55c7-41b7-8a48-43bea9ab4411

**Comment by Monster-Zer0** [comment]
same issue

https://aofpaste.com/uyoyixewas.properties

looks like a ticking entity issue.

**Comment by 1028sx** [comment]
> 

as same as you

**Comment by VulpesStella** [comment]
Does this crash only appear in the fabric version?

**Comment by ardissaps** [comment]
Didn't tested on forge, I only tested on Fabric.
